spring.application.name=PaystackDemo

paystack.secret-key = sk_test_1f696959f775c244bbf501a36a1f7f1d001865ae
paystack.base-url = https://api.paystack.co

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/PaystackDemo
spring.datasource.username=postgres
spring.datasource.password=Stuntinoh9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

