spring.application.name=PaystackDemo

paystack.secret-key = ${SECRET_KEY}
paystack.base-url = https://api.paystack.co

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/PaystackDemo
spring.datasource.username=postgres
spring.datasource.password=Stuntinoh9

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

